Add docker compose resources for obbi profile AU spec
wso2/docker-open-banking pull request #110
Opened 2021-08-03 11:51 UTC by imesh94

## Purpose
> This PR adds resources required for running wso2-obbi profile for OB AU specification.

2021-08-03 17:18 UTC, chirangaalwis requested changes

2021-08-03 17:18 UTC, chirangaalwis commented on docker-compose/obam-obiam-with-obbi/obbi/au/bin/dashboard.sh
> +exit;
@imesh94 please add an EOF line.

2021-08-03 17:18 UTC, chirangaalwis commented on docker-compose/obam-obiam-with-obbi/obbi/au/bin/dashboard.sh
> +exit;
Check other files as well.

2021-08-04 04:42 UTC, imesh94 commented on docker-compose/obam-obiam-with-obbi/obbi/au/bin/dashboard.sh
> +exit;
done

2021-08-04 11:37 UTC, chirangaalwis approved these changes

2021-08-04 11:40 UTC, merged