Changing the dockerfiles to use with multiple base product versions.
wso2/docker-open-banking pull request #154
Opened 2023-04-26 11:16 UTC by Chathuratharushka

## Purpose
> This PR will change dockerfiles to use them with multiple base product versions.

changes which have done in this PR :

- Passing another build argument (BASE_PRODUCT_VERSION)  when building the docker images to specify the base product version.
- Removing IS connector from obiam docker images and updating the instructions about volume mounting them on the obiam container.
- adding another sql script (setup-apim4.2.0-IS6.0.0) for the APIM 4.2.0 and IS 6.0.0
- adding new java keystores(private-keys.jks & public-certs.jks) to keep hostname changed wso2 server certs.

Issue link: https://github.com/wso2-enterprise/financial-open-banking/issues/8203
## Goals
> Describe the solutions that this feature/fix will introduce to resolve the problems described above

## Approach
> Describe how you are implementing the solutions. Include an animated GIF or screenshot if the change affects the UI (email documentation@wso2.com to review all UI text). Include a link to a Markdown file or Google doc if the feature write-up is too long to paste here.

## User stories
> Summary of user stories addressed by this change>

## Release note
> Brief description of the new feature or bug fix as it will appear in the release notes

## Documentation
> Link(s) to product documentation that addresses the changes of this PR. If no doc impact, enter “N/A” plus brief explanation of why there’s no doc impact

## Training
> Link to the PR for changes to the training content in https://github.com/wso2/WSO2-Training, if applicable

## Certification
> Type “Sent” when you have provided new/updated certification questions, plus four answers for each question (correct answer highlighted in bold), based on this change. Certification questions/answers should be sent to certification@wso2.com and NOT pasted in this PR. If there is no impact on certification exams, type “N/A” and explain why.

## Marketing
> Link to drafts of marketing content that will describe and promote this feature, including product page changes, technical articles, blog posts, videos, etc., if applicable

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   > Details about the test cases and coverage

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes/no
 - Ran FindSecurityBugs plugin and verified report? yes/no
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes/no

## Samples
> Provide high-level details about the samples related to this feature

## Related PRs
> List any other related PRs

## Migrations (if applicable)
> Describe migration steps and platforms on which migration has been tested

## Test environment
> List all JDK versions, operating systems, databases, and browser/versions on which this feature/fix was tested
 
## Learning
> Describe the research phase and any blog posts, patterns, libraries, or add-ons you used to solve the problem.

2023-05-10 12:55 UTC, hasithakn approved these changes

2023-05-11 05:19 UTC, hasithakn submitted a review, later dismissed

2023-05-11 10:13 UTC, DivyaPremanantha requested changes
As discussed offline please do the following changes,

01. No need to duplicate Docker compose, we can request to modify the image name through the READ.ME file, so please remove the toolkit docker componse files.
02. Move keystores in to the dockerfiles folder

2023-05-11 14:26 UTC, hasithakn approved these changes

2023-05-12 04:39 UTC, DivyaPremanantha approved these changes

2023-05-12 04:49 UTC, merged